services:
  - type: docker
    name: java-app
    dockerfilePath: Dockerfile
    dockerCommand: docker-compose up --build
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
