services:
  - type: web
    runtime: docker
    name: java-app
    dockerfilePath: docker-compose
    dockerCommand: docker-compose up --build
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
