services:
  - type: web
    name: java-app
    dockerfilePath: Dockerfile
    dockerCommand: docker-compose up --build # Cambia esto según la ruta del JAR en tu Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080