services:
  - type: web
    name: java-app
    env: java
    buildCommand: ./mvnw clean package  # Si usas Maven, este es el comando adecuado
    startCommand: java -jar target/myapp.jar  # Asegúrate de que este sea el nombre correcto del archivo .jar
    plan: free
    regions:
      - oregon  # Escoge la región más cercana
    ports:
      - 8080  # Expone el puerto 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/puzzle?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Configuración de Hibernate
    dependsOn:
      - mysql-db  # Asegura que la base de datos esté lista antes de iniciar la app

  - type: database
    name: mysql-db
    env: mysql
    plan: free
    region: oregon  # Región para la base de datos MySQL
    databaseUrl: mysql://root:root@mysql-db:3306/puzzle  # URL de conexión a la base de datos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: puzzle
    ports:
      - 3307:3306  # Exposición del puerto de la base de datos
